In [1]:
# 사용할 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 시각화 전 기본 세팅
#한글 깨짐
plt.rc("font", family="Malgun Gothic")

In [2]:
# 파일 불러오기
sample_submission = pd.read_csv('data/sample_submission.csv', index_col='no')
test = pd.read_csv('data/test.csv', index_col='no')
train = pd.read_csv('data/train.csv', index_col='no')

## 예측할 값 : 개인 소득
- income : 50K 초과는 1, 50K 이하는 0 (소득)

### 컬럼 의미
- age - continuous.
- workclass(일 유형) : Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt(일련의 관측 결과를 바탕으로 인구조사국이 부여하는 개인의 가중치): continuous.
- education(교육수준) : Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num(교육수준 번호) : continuous.
- marital-status(결혼 상태) : Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation(직업) : Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship(가족관계) : Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race(인종) : White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex(성별) : Female, Male.
- capital-gain(자본 이익) : continuous.
- capital-loss(자본 손실) : continuous.
- hours-per-week(주당 근무 시간) : continuous.
- native-country(국적) : United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

### value값 띄어쓰기 제거

In [3]:
# 띄어쓰기 제거함
for i in train.columns : 
    if train[f'{i}'].dtype == 'object' :
        train[f'{i}'] = train[f'{i}'].apply(lambda x: x.replace(' ', '')) # 제거하는 함수
    else :
        train[f'{i}'] = train[f'{i}']
        
for i in test.columns : 
    if test[f'{i}'].dtype == 'object' :
        test[f'{i}'] = test[f'{i}'].apply(lambda x: x.replace(' ', '')) # 제거하는 함수
    else :
        test[f'{i}'] = test[f'{i}']

In [4]:
title=['Private', 'Self-emp-not-inc', 'Local-gov', '?',
       'State-gov', 'Self-emp-inc','Federal-gov','Without-pay','Never-worked']
cover_title=['Private', 'Self-emp-not-inc', 'Local-gov', 'Private',
       'State-gov', 'Self-emp-inc','Federal-gov','Without-pay','Never-worked']
title_dict = dict(zip(title, cover_title))
title_dict
train['workclass'] = train['workclass'].map(title_dict)

title=['?', 'Private', 'Self-emp-not-inc', 'Local-gov', 'Self-emp-inc',
       'State-gov', 'Federal-gov', 'Without-pay', 'Never-worked']
cover_title=['Private', 'Private', 'Self-emp-not-inc', 'Local-gov', 'Self-emp-inc',
       'State-gov', 'Federal-gov', 'Without-pay', 'Never-worked']
title_dict = dict(zip(title, cover_title))
title_dict
test['workclass'] =test['workclass'].map(title_dict)

In [5]:
title=['United-States', 'Haiti', 'Mexico', 'Puerto-Rico', 'Philippines',
       '?', 'Germany', 'Peru', 'Ecuador', 'Iran', 'Thailand',
       'Dominican-Republic', 'Poland', 'Scotland', 'Italy', 'Jamaica',
       'China', 'Portugal', 'Columbia', 'Hungary', 'Vietnam', 'Taiwan',
       'Canada', 'Hong', 'Guatemala', 'El-Salvador', 'England',
       'Outlying-US(Guam-USVI-etc)', 'India', 'France', 'Cuba', 'Greece',
       'Trinadad&Tobago', 'South', 'Japan', 'Yugoslavia', 'Nicaragua',
       'Ireland', 'Cambodia', 'Laos', 'Honduras', 'Holand-Netherlands']
cover_title=['United-States', 'Haiti', 'Mexico', 'Puerto-Rico', 'Philippines',
       'United-States', 'Germany', 'Peru', 'Ecuador', 'Iran', 'Thailand',
       'Dominican-Republic', 'Poland', 'Scotland', 'Italy', 'Jamaica',
       'China', 'Portugal', 'Columbia', 'Hungary', 'Vietnam', 'Taiwan',
       'Canada', 'Hong', 'Guatemala', 'El-Salvador', 'England',
       'Outlying-US(Guam-USVI-etc)', 'India', 'France', 'Cuba', 'Greece',
       'Trinadad&Tobago', 'South', 'Japan', 'Yugoslavia', 'Nicaragua',
       'Ireland', 'Cambodia', 'Laos', 'Honduras', 'Holand-Netherlands']
title_dict = dict(zip(title, cover_title))
title_dict
train['native-country'] = train['native-country'].map(title_dict)

title=['United-States', 'Puerto-Rico', 'Portugal', '?', 'El-Salvador',
       'Iran', 'India', 'Philippines', 'Vietnam', 'Cuba', 'Italy',
       'Hungary', 'Jamaica', 'Germany', 'Mexico', 'England', 'Columbia',
       'China', 'Nicaragua', 'Taiwan', 'Scotland', 'Ireland', 'Poland',
       'South', 'France', 'Guatemala', 'Japan', 'Canada', 'Ecuador',
       'Dominican-Republic', 'Yugoslavia', 'Haiti', 'Greece',
       'Outlying-US(Guam-USVI-etc)', 'Laos', 'Trinadad&Tobago',
       'Thailand', 'Peru', 'Honduras', 'Hong', 'Cambodia']
cover_title=['United-States', 'Puerto-Rico', 'Portugal', 'United-States', 'El-Salvador',
       'Iran', 'India', 'Philippines', 'Vietnam', 'Cuba', 'Italy',
       'Hungary', 'Jamaica', 'Germany', 'Mexico', 'England', 'Columbia',
       'China', 'Nicaragua', 'Taiwan', 'Scotland', 'Ireland', 'Poland',
       'South', 'France', 'Guatemala', 'Japan', 'Canada', 'Ecuador',
       'Dominican-Republic', 'Yugoslavia', 'Haiti', 'Greece',
       'Outlying-US(Guam-USVI-etc)', 'Laos', 'Trinadad&Tobago',
       'Thailand', 'Peru', 'Honduras', 'Hong', 'Cambodia']
title_dict = dict(zip(title, cover_title))
title_dict
test['native-country'] = test['native-country'].map(title_dict)

In [6]:
title=['Machine-op-inspct', 'Other-service', 'Handlers-cleaners',
       'Tech-support', 'Transport-moving', 'Farming-fishing',
       'Prof-specialty', 'Priv-house-serv', 'Adm-clerical',
       'Protective-serv', 'Exec-managerial', '?', 'Craft-repair', 'Sales',
       'Armed-Forces']
cover_title=['Machine-op-inspct', 'Other-service', 'Handlers-cleaners',
       'Tech-support', 'Transport-moving', 'Farming-fishing',
       'Prof-specialty', 'Priv-house-serv', 'Adm-clerical',
       'Protective-serv', 'Exec-managerial', 'Prof-specialty', 'Craft-repair', 'Sales',
       'Armed-Forces']
title_dict = dict(zip(title, cover_title))
title_dict
train['occupation'] = train['occupation'].map(title_dict)

title=['?', 'Other-service', 'Tech-support', 'Exec-managerial',
       'Farming-fishing', 'Sales', 'Adm-clerical', 'Craft-repair',
       'Handlers-cleaners', 'Machine-op-inspct', 'Protective-serv',
       'Prof-specialty', 'Transport-moving', 'Priv-house-serv',
       'Armed-Forces']
cover_title=['Prof-specialty', 'Other-service', 'Tech-support', 'Exec-managerial',
       'Farming-fishing', 'Sales', 'Adm-clerical', 'Craft-repair',
       'Handlers-cleaners', 'Machine-op-inspct', 'Protective-serv',
       'Prof-specialty', 'Transport-moving', 'Priv-house-serv',
       'Armed-Forces']
title_dict = dict(zip(title, cover_title))
title_dict
test['occupation'] = test['occupation'].map(title_dict)

In [7]:
train = train.drop('education',axis=1)
test = test.drop('education',axis=1)

In [8]:
marital_status = ['Divorced', 'Never-married', 'Married-civ-spouse', 'Separated',
       'Married-spouse-absent', 'Widowed', 'Married-AF-spouse']
conver_marital_status = ['not-married', 'not-married', 'married', 'not-married', 'not-married', 'not-married','married']
marital_status_dict=dict(zip(marital_status, conver_marital_status))

train['marital-status']=train['marital-status'].map(marital_status_dict)
test['marital-status']=test['marital-status'].map(marital_status_dict)

In [9]:
train['relationship'].unique()
title=['Not-in-family', 'Husband', 'Unmarried', 'Other-relative',
       'Own-child', 'Wife']
cover_title=['Not-in-family', 'Married', 'Unmarried', 'Other-relative',
       'Own-child', 'Married']
title_dict = dict(zip(title, cover_title))
train['relationship'] = train['relationship'].map(title_dict)

title=['Own-child', 'Wife', 'Husband', 'Not-in-family', 'Unmarried',
       'Other-relative']
cover_title=['Own-child', 'Married', 'Married', 'Not-in-family', 'Unmarried',
       'Other-relative']
title_dict = dict(zip(title, cover_title))
test['relationship'] = test['relationship'].map(title_dict)

In [10]:
bins = [0,4,8,12,16] # 범위지정
labels = ['e1', 'e2', 'e3', 'e4'] # 라벨지정
train['education-num'] = pd.cut(train['education-num'], bins=bins, labels = labels)
test['education-num'] = pd.cut(test['education-num'], bins=bins, labels=labels)

In [11]:
#  사회 초년생 - age1 [17~30]
age1 = [i for i in range(17, 31)]
cover_age1 = ['young'] * (31-17)

#  중년층 - age2 [31~50]
age2 = [i for i in range(31, 51)]
cover_age2 = ['middle'] * (51-31)

# 노년층 - age3 [51 ~ 90]
age3 = [i for i in range(51, 91)]
cover_age3 = ['old'] * (91-51)

In [12]:
age_dict = dict(zip(age1 + age2 + age3, cover_age1 + cover_age2 + cover_age3))

train['age']=train['age'].map(age_dict)
test['age']=test['age'].map(age_dict)

In [13]:
title=['Private', 'Self-emp-not-inc', 'Local-gov', 'State-gov',
       'Self-emp-inc', 'Federal-gov', 'Without-pay', 'Never-worked']
cover_title=['Private', 'Self-emp', 'gov', 'gov',
       'Self-emp', 'gov', 'beggar', 'beggar']
title_dict = dict(zip(title, cover_title))
train['workclass'] = train['workclass'].map(title_dict)

title=['Private', 'Self-emp-not-inc', 'Local-gov', 'Self-emp-inc',
       'State-gov', 'Federal-gov', 'Without-pay', 'Never-worked']
cover_title=['Private', 'Self-emp', 'gov', 'Self-emp',
       'gov', 'gov', 'beggar', 'beggar']
title_dict = dict(zip(title, cover_title))
test['workclass'] = test['workclass'].map(title_dict)

In [14]:
native_country = ['United-States', 'Haiti', 'Mexico', 'Puerto-Rico', 'Philippines',
       'Germany', 'Peru', 'Ecuador', 'Iran', 'Thailand',
       'Dominican-Republic', 'Poland', 'Scotland', 'Italy', 'Jamaica',
       'China', 'Columbia', 'Hungary', 'Portugal', 'Vietnam', 'Taiwan',
       'Canada', 'Hong', 'Guatemala', 'El-Salvador', 'England',
       'Outlying-US(Guam-USVI-etc)', 'India', 'France', 'Cuba', 'Greece',
       'Trinadad&Tobago', 'South', 'Japan', 'Yugoslavia', 'Nicaragua',
       'Ireland', 'Cambodia', 'Laos', 'Honduras', 'Holand-Netherlands']
conver_native_country = ['North America', 'North America', 'Asia', 'Europe', 'North America',
                         'North America', 'North America', 'North America', 'Asia', 'Europe',
                         'North America', 'Asia', 'Asia', 'North America', 'Europe',
                         'Asia', 'South America', 'North America', 'Asia', 'Europe',
                        'North America', 'Europe', 'Asia', 'Asia', 'North America',
                         'South America', 'Europe', 'Europe', 'South America', 'Asia',
                         'Europe', 'Asia', 'North America', 'Asia', 'Europe',
                         'Asia', 'South America', 'Europe', 'North America', 'Europe', 'Europe']

native_country_dict = dict(zip(native_country, conver_native_country))
native_country_dict
train['native-country']=train['native-country'].map(native_country_dict)
test['native-country']=test['native-country'].map(native_country_dict)

In [1]:
train['native-country'].unigue()

NameError: name 'train' is not defined

In [15]:
train = train.drop('fnlwgt',axis=1)

In [16]:
test= test.drop('fnlwgt',axis=1)

- 컬럼순서 바꾸기

In [17]:
train

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
no,,,,,,,,,,,,,
1,young,Private,e2,not-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,North America,0
2,middle,Private,e3,not-married,Other-service,Not-in-family,White,Female,0,1721,55,North America,0
3,middle,Private,e4,not-married,Handlers-cleaners,Not-in-family,Asian-Pac-Islander,Female,0,0,50,North America,0
4,old,Private,e3,not-married,Tech-support,Not-in-family,White,Female,0,0,40,North America,0
5,young,Private,e3,married,Transport-moving,Married,White,Male,0,0,70,North America,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29301,young,Private,e3,not-married,Sales,Own-child,Other,Male,0,0,40,Europe,0
29302,young,Private,e3,not-married,Sales,Own-child,Black,Male,0,0,40,North America,0
29303,young,Self-emp,e2,not-married,Farming-fishing,Own-child,White,Male,0,0,40,North America,0
29304,middle,Private,e2,not-married,Craft-repair,Not-in-family,White,Male,0,0,65,North America,0
29305,old,Private,e3,not-married,Prof-specialty,Not-in-family,White,Female,0,0,40,North America,0

In [18]:
# 문제/답 분리
X_train = train.loc[:,:'native-country']
y_train = train['income']

In [19]:
X_train

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
no,,,,,,,,,,,,
1,young,Private,e2,not-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,North America
2,middle,Private,e3,not-married,Other-service,Not-in-family,White,Female,0,1721,55,North America
3,middle,Private,e4,not-married,Handlers-cleaners,Not-in-family,Asian-Pac-Islander,Female,0,0,50,North America
4,old,Private,e3,not-married,Tech-support,Not-in-family,White,Female,0,0,40,North America
5,young,Private,e3,married,Transport-moving,Married,White,Male,0,0,70,North America
...,...,...,...,...,...,...,...,...,...,...,...,...
29301,young,Private,e3,not-married,Sales,Own-child,Other,Male,0,0,40,Europe
29302,young,Private,e3,not-married,Sales,Own-child,Black,Male,0,0,40,North America
29303,young,Self-emp,e2,not-married,Farming-fishing,Own-child,White,Male,0,0,40,North America
29304,middle,Private,e2,not-married,Craft-repair,Not-in-family,White,Male,0,0,65,North America
29305,old,Private,e3,not-married,Prof-specialty,Not-in-family,White,Female,0,0,40,North America

In [20]:
y_train

no
1        0
2        0
3        0
4        0
5        1
        ..
29301    0
29302    0
29303    0
29304    0
29305    0
Name: income, Length: 29305, dtype: int64

In [21]:
X_one_hot = pd.get_dummies(X_train) # 0과 1로만 이루어진 열을 생성
X_one_hot

,capital-gain,capital-loss,hours-per-week,age_middle,age_old,age_young,workclass_Private,workclass_Self-emp,workclass_beggar,workclass_gov,...,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male,native-country_Asia,native-country_Europe,native-country_North America,native-country_South America
no,,,,,,,,,,,,,,,,,,,,,
1,0,0,40,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,1,0
2,0,1721,55,1,0,0,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
3,0,0,50,1,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
4,0,0,40,0,1,0,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
5,0,0,70,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29301,0,0,40,0,0,1,1,0,0,0,...,0,0,1,0,0,1,0,1,0,0
29302,0,0,40,0,0,1,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0
29303,0,0,40,0,0,1,0,1,0,0,...,0,0,0,1,0,1,0,0,1,0
29304,0,0,65,1,0,0,1,0,0,0,...,0,0,0,1,0,1,0,0,1,0
29305,0,0,40,0,1,0,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [23]:
knn_model = KNeighborsClassifier(n_neighbors=5)
tree_model = DecisionTreeClassifier(max_depth=5)

In [24]:
result = cross_val_score(tree_model,X_one_hot,y_train,cv = 5)
result

array([0.84610135, 0.8536086 , 0.84541887, 0.84422454, 0.84183586])

In [25]:
result.mean()

0.8462378433714383

In [26]:
result2 = cross_val_score(knn_model,X_one_hot,y_train,cv = 5)
result2

array([0.84678383, 0.85070807, 0.83722914, 0.84576011, 0.84644259])

In [27]:
knn_model.fit(X_one_hot,y_train)
tree_model.fit(X_one_hot,y_train)

DecisionTreeClassifier(max_depth=5)

In [28]:
X_test = pd.get_dummies(test) # 0과 1로만 이루어진 열을 생성
X_test

,capital-gain,capital-loss,hours-per-week,age_middle,age_old,age_young,workclass_Private,workclass_Self-emp,workclass_beggar,workclass_gov,...,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male,native-country_Asia,native-country_Europe,native-country_North America,native-country_South America
no,,,,,,,,,,,,,,,,,,,,,
29306,0,0,16,0,0,1,1,0,0,0,...,0,0,0,1,0,1,0,0,1,0
29307,0,0,40,0,0,1,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
29308,0,0,40,1,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0
29309,0,0,40,1,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,1,0
29310,0,1902,40,1,0,0,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48838,0,0,60,1,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,1,0
48839,0,0,50,1,0,0,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
48840,4386,0,40,0,1,0,1,0,0,0,...,0,0,0,1,0,1,0,0,1,0
48841,0,0,20,0,0,1,1,0,0,0,...,0,0,0,1,1,0,0,0,1,0
48842,0,0,46,1,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,1,0

In [29]:
pre = tree_model.predict(X_test)
pre2 = knn_model.predict(X_test)

In [30]:
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('tree_model2.csv', index = False)

In [31]:
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre2
result.to_csv('knn_model2.csv', index = False)

- min-max scaler적용하기

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [33]:
X_train= X_one_hot

In [34]:
mm_scaler = MinMaxScaler()
mm_scaler.fit(X_train)

MinMaxScaler()

In [35]:
mm_transform_X_train = mm_scaler.transform(X_train)
mm_transform_X_train = pd.DataFrame(mm_transform_X_train, columns=X_train.columns)
mm_transform_X_test = mm_scaler.transform(X_test)
mm_transform_X_test = pd.DataFrame(mm_transform_X_test, columns=X_test.columns)

In [36]:
result = cross_val_score(knn_model,
                          mm_transform_X_train,
                          y_train,
                          cv = 5)

In [37]:
result.mean()

0.8232383552294831

In [38]:
knn_model.fit(mm_transform_X_train,y_train)
pre = knn_model.predict(mm_transform_X_test)

In [39]:
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('knn_model_mm2.csv', index = False)

- 앙상블

In [40]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

In [41]:
# 랜덤포레스트 모델 생성
rf_model = RandomForestClassifier(n_estimators=1000,  # 결정트리의 개수
                                 max_depth=5,         # 트리의 최대 깊이
                                 min_samples_leaf=15, # 리프노드가 되기 위한 최소한의 샘플 데이터 수
                                 max_leaf_nodes=50)   # 리프노드의 최대 개수

In [42]:
#교차검증 확인
result = cross_val_score(rf_model,
                          X_train,
                          y_train,
                          cv = 5)

In [43]:
result.mean()

0.842006483535233

In [44]:
# 학습
rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, max_leaf_nodes=50, min_samples_leaf=15,
                       n_estimators=1000)

In [45]:
# 예측
pre = rf_model.predict(X_test)

In [46]:
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('rf_model2.csv', index = False)

- 보팅

In [47]:
# 모델 생성
knn_model = KNeighborsClassifier(n_neighbors=5)
tree_model = DecisionTreeClassifier(max_depth=5)
forest_model = RandomForestClassifier(n_estimators=1000,
                                 max_depth=5,         
                                 min_samples_leaf=15,
                                 max_leaf_nodes=50)

In [48]:
knn_model.fit(mm_transform_X_train,y_train)
tree_model.fit(X_train,y_train)
forest_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, max_leaf_nodes=50, min_samples_leaf=15,
                       n_estimators=1000)

In [49]:
voting_model = VotingClassifier(
                    estimators=[
                        ('knn',knn_model),
                        ('tree',tree_model),
                        ('forest',forest_model)
                    ],
                    voting='soft'
                )

In [50]:
# 교차검증 확인
result = cross_val_score(voting_model,
                          X_train,
                          y_train,
                          cv = 5)
result.mean()

0.8567821190923052

In [51]:
# 학습
voting_model.fit(X_train,y_train)
# 예측
pre = voting_model.predict(X_test)

In [52]:
# 정답제출
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('voting_model2.csv', index = False)

- 부스팅

In [53]:
# AdaBoost모델생성
Ada_model = AdaBoostClassifier(n_estimators=100)

In [54]:
# 교차검증
result = cross_val_score(Ada_model,
                          X_train,
                          y_train,
                          cv = 5)
result.mean()

0.8577034635727692

In [55]:
# 학습
Ada_model.fit(X_train,y_train)
# 예측
pre = Ada_model.predict(X_test)

In [56]:
# 정답제출
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('ada_model2.csv', index = False)

In [57]:
# 모델 생성
final_rf_model = RandomForestClassifier(max_depth=20,
                                        max_leaf_nodes=80,
                                        min_samples_leaf=10,
                                        n_estimators=1500)

In [58]:
result = cross_val_score(final_rf_model,
                          X_train,
                          y_train,
                          cv = 5)

In [59]:
result.mean()

0.8532673605186828

In [60]:
final_rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, max_leaf_nodes=80, min_samples_leaf=10,
                       n_estimators=1500)

In [61]:
pre = final_rf_model.predict(X_test)

In [62]:
# 정답제출
result = pd.read_csv('data/sample_submission.csv')
result['income'] = pre
result.to_csv('final_rf_model2.csv', index = False)